// <auto-generated />
using System;
using Fleet.Modules.Vehicles.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fleet.Modules.Vehicles.Persistence.Migrations
{
    [DbContext(typeof(VehiclesDbContext))]
    [Migration("20260908083128_InitialVehicles")]
    partial class InitialVehicles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("vehicles")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fleet.Modules.Vehicles.Domain.Depot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("city");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_depots");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_depots_name");

                    b.ToTable("depots", "vehicles");
                });

            modelBuilder.Entity("Fleet.Modules.Vehicles.Domain.OdometerReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Km")
                        .HasColumnType("integer")
                        .HasColumnName("km");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_odometer_readings");

                    b.HasIndex("VehicleId", "RecordedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_odometer_readings_vehicle_id_recorded_at");

                    b.ToTable("odometer_readings", "vehicles");
                });

            modelBuilder.Entity("Fleet.Modules.Vehicles.Domain.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DepotId")
                        .HasColumnType("uuid")
                        .HasColumnName("depot_id");

                    b.Property<DateTimeOffset?>("LastReadingAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reading_at");

                    b.Property<int>("OdometerKm")
                        .HasColumnType("integer")
                        .HasColumnName("odometer_km");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("plate");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("DepotId")
                        .HasDatabaseName("ix_vehicles_depot_id");

                    b.HasIndex("Plate")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicles_plate");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_vehicles_status");

                    b.ToTable("vehicles", "vehicles");
                });

            modelBuilder.Entity("Fleet.Modules.Vehicles.Domain.OdometerReading", b =>
                {
                    b.HasOne("Fleet.Modules.Vehicles.Domain.Vehicle", null)
                        .WithMany("OdometerReadings")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_odometer_readings_vehicles_vehicle_id");
                });

            modelBuilder.Entity("Fleet.Modules.Vehicles.Domain.Vehicle", b =>
                {
                    b.HasOne("Fleet.Modules.Vehicles.Domain.Depot", "Depot")
                        .WithMany()
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_depots_depot_id");

                    b.Navigation("Depot");
                });

            modelBuilder.Entity("Fleet.Modules.Vehicles.Domain.Vehicle", b =>
                {
                    b.Navigation("OdometerReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
